language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Fp3IXmZrdhdebnPM81bHDEQ8y7BG4yOXpFyz2pYOmzTVyeY2JAfFpdy+p+2P2VE898pgKsmKc+F4mrGHWGduBb0IlugysTI+YFrFCVpaq13K4xqQQI63+obNSxS2xoMU1/cGbLJU6JLZU1pBuiNzdIanRRpveO0QFYc7qwsFpXsMH8HsWaBv0o/C7XSMOkO7vSsm/UdKf92yVmJIAUKkEGWArKIFQg7FQ1leJc1suSV/AZRoE+zACwJVDztxYQOXA+jJL9qHji7d69OBztwLUXLy/CowEjzFzw1ukBzLuPGrYvU7+KKqGhvqd61XUC3jxZIB0B4CNeM/guSy0KLQYNyZ8vu3mUV3S9wgA7mHJoQPLpRVdJWTNbIviJh2h01tcvehD0EZ47tjQU9e9sDSrz/X+0HW2O5v03d3RSgWIeXq0pwtkZYSr/CxXcxuDeUCtKLT8VicvHb3skLOC6ec1ZWynB6VW4NgexvrK4FeKK5J+juIGjGdkVem/1oW0ntveTPDEneCFwbUK3+OFnPjnVksaydP8RflJxFFO9LgrfHa453j8TnXgOlHF+iHt5mDGxh4Ebaz8IoQuRBWNMHsNQc9P436Ha2v+j3whlr7URB9DtOealDcqKeb5TWJRaHf/wroGoRNfp9I+MOGMXs0Hja6PfF6/5oW70F02Yt9RuE=
  - secure: m/lNXKgR2mc4GRn1C0VvAve5tiOhzEuS0nMe+KKB60WPfDnZoSrOKHNx21gzePeUobWSEku7c58cK80lbUFZ+YVgjXA8F5ibwbWgGsRavTdo9OQVl/F0sdWvcQ6OZyAFydVe430aDcH8QqF5vw5xFYRxsvUpX9xt9lOm20rpOTVD1Oy0zIMxeXsA3j/2uBWIZxbFgKjctwodcke63EOwY29Sa1lTVi9kQtskTUMiZTHEqpPGJCa7yB22wCEGdrHoG2agUO5nzLAXFdq3TC2BIO+ZkM3lus2gKmNjNl0wWTceKb3NvtbxNKLNmgwAZZ9o5dHmbHV/pqU8YmmDpvpRe5eMhmTiZo/RER3WYrqhiUDFJiP6heR/NVKuowsXsc73aVVU+ZI4QJOILCDFeqQbdaDdFN0EhixT/q02MvT71AzBK8RANnfgibCARJN9/eXhOrA5xl0Hcd+ohmnNg2eJmbnLur0HTkeMhG2Rv4KO5ATHtoWZlfFvm3FgDeABjmV3Gb7kwACPbUTc73IGLnSjxogTPpB9gHF0fNQqodF2GwU4aVGgHS39eYW+HJdjQ3IyjQeY9gnTUCLPwwwZ5Qe+Djxrvkf2CLCuTXTAuE7MdOsw0DxV17uXrn54v1b1bIqlps6GkdH9bykYo0WZ7O8mCSQ83DGIyXP29l84Ec3Yd8g=
